JoinTokens = true
TryBypassCaptcha = false  

Threads = 10    
DelayOnStart = 75  
SleepAfterXDM = 9  
DelayOnMessage = 70  
DelayOnRatelimit = 600  
MaxDMOpensPerToken = 600  

MongoURL = "mongodb+srv://user:pass@cluster0.pyabp0c.mongodb.net/test"  
#Oficial suporte api.anti-captcha.com, api.capsolver.com, api.capmonster.cloud  

KeyCaptchaForDM = "CAI-xxxx"  
DomainCaptchaForDM = "api.capsolver.com"  
  
KeyCaptchaForJoin = "xxxxx"  
DomainCaptchaForJoin = "api.anti-captcha.com"
